pipeline:
  check:
    image: python
    commands:
      - curl -sSL https://install.python-poetry.org | python3 -
      - /root/.local/bin/poetry install
      - /root/.local/bin/poetry run alembic upgrade head
      - /root/.local/bin/poetry run make test
      - /root/.local/bin/poetry run pdoc --html --output-dir build app
    environment:
      DB_URL: "cockroachdb://root@database:26257/defaultdb"
      IPFS_URL: "http://cluster:9094"
      SECRET: "1234"
  pin-cluster:
    image: cofob/ipfs-cluster-ctl
    commands:
      - ipfs-cluster-ctl --host /dns4/rat.frsqr.xyz/tcp/9094 --basic-auth default:$CLUSTER_SECRET add -r --expire-in 2160h --name api/docs/$(date +%s) -Q build/app/ > cid.txt
      - cat cid.txt
      - echo "https://ipfsqr.ru/ipfs/$(cat cid.txt)"
    secrets: [CLUSTER_SECRET]

services:
  database:
    image: cockroachdb/cockroach:v22.1.7
    commands:
      - /cockroach/cockroach start-single-node --insecure
  ipfs:
    image: ipfs/kubo
  cluster:
    image: ipfs/ipfs-cluster
    environment:
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
