"""Add password and verifed fields

Revision ID: 97a011dc86de
Revises: d3409f086e74
Create Date: 2022-10-02 03:07:54.588275

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "97a011dc86de"
down_revision = "d3409f086e74"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("password", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False)
    )
    op.add_column("user", sa.Column("verifed", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "verifed")
    op.drop_column("user", "password")
    # ### end Alembic commands ###
